### ISSUE TITLE
是否有dropbox或其他下载链接

### ISSUE THREAD

**Issue by lidh15** [wonderseen/PCKMT#1]
check point及其他文件有十几个G，百度网盘没有会员只有100KB/s基本无法下载下来

**Comment by wonderseen** [comment]
hi, 不好意思，目前不太方便使用网盘付费长期维护大文件。

Tips:

如需节省下载时间，可以仅下载网盘中的 `PCKMT/model_record_path/${DOMAIN}/knn_transfere_nce_64/checkpoint_best.pt`，每个DOMAIN的checkpoint大小为1.35G。基于此，可生成其他checkpoint和datastore文件，流程如下：



将下载的checkpoint文件夹置于codes目录下：

```shell
cd ${本仓库本地根目录}/codes/
mv ${下载目录}/PCKMT/model_record_path .
```



确保形如以下目录排布：

```shell
PCKMT/
└── codes
    └── model_record_path
        └── it
            └── knn_transfered_nce_64
                └── checkpoint_best.pt
```



接着，依次对每个domain，按照[README](https://github.com/wonderseen/PCKMT)执行datastore生成和翻译模型的训练，可生成网盘中其他所有文件。

```shell
# 6.Reconstruct the compressed datastore of CKMT
. create_datastore_knn_align.sh

# 7.Train the quantized index
. build_faiss_index_knn_align.sh

# 8.Train the CKMT model
. train_faiss_knn_align.sh
```

**Comment by lidh15** [comment]
好的，谢谢。
