### ISSUE TITLE
请问算法时间空间复杂度大概是怎样的？

### ISSUE THREAD

**Issue by lidh15** [wonderseen/PCKMT#3]
根据提供的日志资料来看整个训练流程完成一遍耗时不会太长，我之前用一个toy data进行测试后也可以很快完成。
但是当换成大规模数据后耗时大大增加，请问耗时随数据规模如何变化？
可选的prune datastore步骤是否会有助于加速后续步骤？

**Comment by lidh15** [comment]
例如knn align这一步，在fairseq训练开始前，处理target token embedding时提供的参考log里耗时大概一分钟，但是我实际运行时这一步耗时需要数小时，让我常常怀疑是否已经停止运行。

**Comment by lidh15** [comment]
在空间方面，在train faiss knn align这一步，fairseq一直报错out of memory，我尝试将gpu ids改成多块卡，但是faiss又会报错index在gpu上数据在cpu上，尝试调整其他参数但是都没有解决问题。

**Comment by wonderseen** [comment]
knn_align首先对target token embedding进行dbscan聚类预处理后才执行训练。聚类过程中，对于每个cluster family，dbscan对应的平均查询复杂度是O(nlog(n))，空间复杂度O(n)，n是cluster family内部节点数目。具体您可以回溯dbscan的算法分析。为了缓解n过大，代码中对n做了上限的限制，在邻域搜索中也限制了搜索超参数。log中只处理时间短是因为datastore规模较小。

不知您datastore具体量级是多少，如果datastore scale过大，可以考虑采用birch[[聚类算法对比]](https://scikit-learn.org/stable/modules/clustering.html#overview-of-clustering-methods)进行聚类，但是对应聚类的精度会有所损失。

prune datastore这个裁剪环节有助于减小datastore的节点数目，总体上对于聚类精度要求不高，因此代码中采用birch进行全量聚类。但是，prune rate和数据的语料的冗余程度直接挂钩，所以需要您根据自己的数据进行调整，经验中大规模datastore上最佳裁剪率分布于10%～30%。

**Comment by wonderseen** [comment]
关于train faiss knn align多卡出错的log可否打印一下？

**Comment by wonderseen** [comment]
针对大规模数据的knn align问题，后续会完善logger打印、高效聚类的自动选项。最近比较忙，需要过几天才有空pr，不好意思哈

**Comment by wonderseen** [comment]
肝了DDP的PR[[link]](https://github.com/wonderseen/PCKMT/commit/3d3d22f018c3cac93a1d1afde5c9a1614839a651)，支持不同batch size+datastore size组合的多卡训练逻辑，可见demo [train_faiss_knn_align_ddp.sh](https://github.com/wonderseen/PCKMT/blob/main/codes/train_faiss_knn_align_ddp.sh)。

**Comment by lidh15** [comment]
> 肝了DDP的PR[[link]](https://github.com/wonderseen/PCKMT/commit/3d3d22f018c3cac93a1d1afde5c9a1614839a651)，支持不同batch size+datastore size组合的多卡训练逻辑，可见demo [train_faiss_knn_align_ddp.sh](https://github.com/wonderseen/PCKMT/blob/main/codes/train_faiss_knn_align_ddp.sh)。

感谢支持，更新这个PR后train faiss knn align步骤成功在多卡上跑起来了。
但是观察日志发现模型似乎没有work，训练过程中打印的loss从13开始下降，降到11左右就不再变化，对比提供的log发现这个阶段的训练loss、ppl等指标确实变化不大，但是提供的log里训练开始时loss和ppl已经达到优秀的水平了，loss都是2左右，loss是11的话模型显然不是可用的翻译模型。
我研读了一下代码，这一步似乎是基于knn align这一步的knn_transfered_nce_64/checkpoint_best.pt继续训练的？knn align这一步我的日志和提供的log对比了一下，acc我的是0.965，和提供的log差不多，loss我的有0.33，比log里的都大一些，这个指标是否说明knn align这一步没有得到合理的结果？

**Comment by lidh15** [comment]
de en使用同一个词表是否是一个必要的条件？我自己的数据和模型为了节省embedding layer空间src和tgt词表都是独立的，不知道不work是否由于这个原因？

**Comment by wonderseen** [comment]
de en的词表一般需要和pretrain model一致，在此基础上可以基于pretrain model对de或者en的词表向量进行裁剪或者约束。

**Comment by wonderseen** [comment]
de en的词表一般需要和pretrain model一致，在此基础上可以基于pretrain model对de或者en的词表向量进行裁剪或者约束。

如果要完全使用自己定义的vocab table，您需要重新训练好一个配对的nmt pretrain model

**Comment by lidh15** [comment]
我检查了我的knn align，有一个疑问，knn align这一步加载的数据为何是valid set？我自己的valid set比较随意，只找了几十句平行语料，所以这一步好像出问题了。

**Comment by wonderseen** [comment]
> 我检查了我的knn align，有一个疑问，knn align这一步加载的数据为何是valid set？我自己的valid set比较随意，只找了几十句平行语料，所以这一步好像出问题了。

这个有点tricky，是一个历史问题，一开始为了方便没有单独写knn align的pipeline，而是直接在adaptive knn-mt的pipeline基础上重写构造knn align的训练过程。knn align不走adaptive knn mt的dataloader和forward，单独走 knn_training_iterator/TripletDatastoreSamplingDataset 和 forward_knn_training 这一路。

因此，训练数据上看，knn align只和keys、vals有关，超参数中其他的mt语料（比如你提到的valid set）不会被用来训练compact network。

具体可见之前的 comment： [line11-19](https://github.com/wonderseen/PCKMT/blob/ce1d6f80502cbfeaf45bc7fb2562b96ad2c7df00/codes/knn_align.sh#L10)

**Comment by lidh15** [comment]
> > 我检查了我的knn align，有一个疑问，knn align这一步加载的数据为何是valid set？我自己的valid set比较随意，只找了几十句平行语料，所以这一步好像出问题了。
> 
> 这个有点tricky，是一个历史问题，一开始为了方便没有单独写knn align的pipeline，而是直接在adaptive knn-mt的pipeline基础上重写构造knn align的训练过程。knn align不走adaptive knn mt的dataloader和forward，单独走 knn_training_iterator/TripletDatastoreSamplingDataset 和 forward_knn_training 这一路。
> 
> 因此，训练数据上看，knn align只和keys、vals有关，超参数中其他的mt语料（比如你提到的valid set）不会被用来训练compact network。
> 
> 具体可见之前的 comment： [line11-19](https://github.com/wonderseen/PCKMT/blob/ce1d6f80502cbfeaf45bc7fb2562b96ad2c7df00/codes/knn_align.sh#L10)

这里18行和19行的注释是说这个读取valid set的步骤只是为了确定训练epoch数吗？是不是相当于我把我的valid set从20句增加到2000句完全等价于我把epoch数从20改成2000？

**Comment by wonderseen** [comment]
> > > 我检查了我的knn align，有一个疑问，knn align这一步加载的数据为何是valid set？我自己的valid set比较随意，只找了几十句平行语料，所以这一步好像出问题了。
> > 
> > 
> > 这个有点tricky，是一个历史问题，一开始为了方便没有单独写knn align的pipeline，而是直接在adaptive knn-mt的pipeline基础上重写构造knn align的训练过程。knn align不走adaptive knn mt的dataloader和forward，单独走 knn_training_iterator/TripletDatastoreSamplingDataset 和 forward_knn_training 这一路。
> > 因此，训练数据上看，knn align只和keys、vals有关，超参数中其他的mt语料（比如你提到的valid set）不会被用来训练compact network。
> > 具体可见之前的 comment： [line11-19](https://github.com/wonderseen/PCKMT/blob/ce1d6f80502cbfeaf45bc7fb2562b96ad2c7df00/codes/knn_align.sh#L10)
> 
> 这里18行和19行的注释是说这个读取valid set的步骤只是为了确定训练epoch数吗？是不是相当于我把我的valid set从20句增加到2000句完全等价于我把epoch数从20改成2000？

 是的。log中打印的epoch数目是valid set被读取的epoch轮次。

**Comment by lidh15** [comment]
那么这个日志里的acc是什么的准确率？我从一般的翻译角度理解分子的数字是train set翻译正确的target token数量，分母是整个train set的target token数量，不知我的理解是否正确？

**Comment by wonderseen** [comment]
> 那么这个日志里的acc是什么的准确率？我从一般的翻译角度理解分子的数字是train set翻译正确的target token数量，分母是整个train set的target token数量，不知我的理解是否正确？

log中acc是batch-level acc。计算的是triplet sampling中分类出negative sample和positive sample两者的正确率，分母是batch中sample pair的总数。

**Comment by lidh15** [comment]
> > 肝了DDP的PR[[link]](https://github.com/wonderseen/PCKMT/commit/3d3d22f018c3cac93a1d1afde5c9a1614839a651)，支持不同batch size+datastore size组合的多卡训练逻辑，可见demo [train_faiss_knn_align_ddp.sh](https://github.com/wonderseen/PCKMT/blob/main/codes/train_faiss_knn_align_ddp.sh)。
> 
> 感谢支持，更新这个PR后train faiss knn align步骤成功在多卡上跑起来了。
> 但是观察日志发现模型似乎没有work，训练过程中打印的loss从13开始下降，降到11左右就不再变化，对比提供的log发现这个阶段的训练loss、ppl等指标确实变化不大，但是提供的log里训练开始时loss和ppl已经达到优秀的水平了，loss都是2左右，loss是11的话模型显然不是可用的翻译模型。
> 我研读了一下代码，这一步似乎是基于knn align这一步的knn_transfered_nce_64/checkpoint_best.pt继续训练的？knn align这一步我的日志和提供的log对比了一下，acc我的是0.965，和提供的log差不多，loss我的有0.33，比log里的都大一些，这个指标是否说明knn align这一步没有得到合理的结果？

经过一周的排查，原来是我同学把激活函数换成了gelu…从来没想过有人会不用relu

**Comment by lidh15** [comment]
> 肝了DDP的PR[[link]](https://github.com/wonderseen/PCKMT/commit/3d3d22f018c3cac93a1d1afde5c9a1614839a651)，支持不同batch size+datastore size组合的多卡训练逻辑，可见demo [train_faiss_knn_align_ddp.sh](https://github.com/wonderseen/PCKMT/blob/main/codes/train_faiss_knn_align_ddp.sh)。

请问test adaptive knn mt knn align这一步是否也可DDP呢？目前测试时报错 
knn_datastore.py in get_knns
torch_utils.py in torch_replacement_search
swigfaiss.py in search
RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /project/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryOverflow dev 0 space Device stream 0 size 18446744072521625600 bytes (cudaMalloc error out of  memory [2])

**Comment by lidh15** [comment]
> > 肝了DDP的PR[[link]](https://github.com/wonderseen/PCKMT/commit/3d3d22f018c3cac93a1d1afde5c9a1614839a651)，支持不同batch size+datastore size组合的多卡训练逻辑，可见demo [train_faiss_knn_align_ddp.sh](https://github.com/wonderseen/PCKMT/blob/main/codes/train_faiss_knn_align_ddp.sh)。
> 
> 请问test adaptive knn mt knn align这一步是否也可DDP呢？目前测试时报错 
> knn_datastore.py in get_knns
> torch_utils.py in torch_replacement_search
> swigfaiss.py in search
> RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /project/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryOverflow dev 0 space Device stream 0 size 18446744072521625600 bytes (cudaMalloc error out of  memory [2])

同时如果在train faiss knn align时如果打开了use gpu to search也会报同样的错误，看来只要faiss使用gpu就会有这个问题，但是faiss使用CPU的话实测下来慢了一百倍，性能实在难以接受

**Comment by wonderseen** [comment]
> > > 肝了DDP的PR[[link]](https://github.com/wonderseen/PCKMT/commit/3d3d22f018c3cac93a1d1afde5c9a1614839a651)，支持不同batch size+datastore size组合的多卡训练逻辑，可见demo [train_faiss_knn_align_ddp.sh](https://github.com/wonderseen/PCKMT/blob/main/codes/train_faiss_knn_align_ddp.sh)。
> > 
> > 
> > 请问test adaptive knn mt knn align这一步是否也可DDP呢？目前测试时报错
> > knn_datastore.py in get_knns
> > torch_utils.py in torch_replacement_search
> > swigfaiss.py in search
> > RuntimeError: Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /project/faiss/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryOverflow dev 0 space Device stream 0 size 18446744072521625600 bytes (cudaMalloc error out of  memory [2])
> 
> 同时如果在train faiss knn align时如果打开了use gpu to search也会报同样的错误，看来只要faiss使用gpu就会有这个问题，但是faiss使用CPU的话实测下来慢了一百倍，性能实在难以接受

1. training：
可以参考一下这个逻辑[[code]](https://github.com/wonderseen/PCKMT/blob/1b56e457c8dda7a96e048c737c5c29a10202c148/codes/fairseq_cli/train_ddp.py#L362)。造成oom的主要原因一般有两个：batch大小和datastore大小。如果训练数据中sequence较长的话，batch也是比较关键的因素。请参考batch_large_faiss_large、batch_small_faiss_large这两个逻辑来做training。

2. inference：
如果datastore太大，可以将faiss datastore加载分装在多块gpu上，具体就是在运行前把CUDA_VISIBLE_DEVICES设置成多卡即可。
